package com.paxotech.selenium.experiment.test;

import org.testng.annotations.Test;

public class TryCatchTest {
	
	/*@Test
	public void test1(){
		
		int x = 100;
		int y = 0;
		
		try{
			int z = x / y;
		}
		catch( ArithmeticException ex){
			System.out.println("I got ArithmeticException");
		}
		catch (Exception ex){
			System.out.println("I got error");
			//ex.printStackTrace();
			throw new RuntimeException("I can not do this");
		}
		finally{
			System.out.println(" I am in finally");
		}
		
		System.out.println("I am running");
		
		
		
	}
	
	@Test
	public void test2(){
		
		int x = 100;
		int y = 10;
		
		int z = x / y;
		
		System.out.println("I am running");
		
		
		
	}
*/
}
